### ISSUE TITLE
Staff Module unable to proceed with registration 

### ISSUE THREAD

**Issue by Tiffceet** [Tiffceet/Sports-Facilities-Management-System#7]
![image](https://user-images.githubusercontent.com/41858005/70389838-c1fa9080-19ff-11ea-82e5-eff012326a16.png)

Program will not proceed from this point, probably due to `while (choice[0] != '1' || choice[0] != '2');`

**Comment by simzeki123** [comment]
opps

**Comment by simzeki123** [comment]
alright imma fix this

**Comment by simzeki123** [comment]
1.Test for invalid ![image](https://user-images.githubusercontent.com/57436668/70392187-304b4d00-1a18-11ea-9f41-5544f4aa3503.png)

2.Test for registration 
![image](https://user-images.githubusercontent.com/57436668/70392202-5e309180-1a18-11ea-9fad-6ae2b5c9490b.png)
